name: Automated tests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        options:
          - test_open_login_page
          - test_open_about_page_from_login_page
          - test_open_login_page_from_about_page
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: test_open_login_page
        if: "github.event.inputs.deployment_target == 'test_open_login_page'"
        run: pytest test_login_page.py::test_open_login_page
      - name: test_open_about_page_from_login_page
        if: "github.event.inputs.deployment_target == 'test_open_about_page_from_login_page'"
        run: pytest test_login_page.py::test_open_about_page_from_login_page
      - name: test_open_login_page_from_about_page
        if: "github.event.inputs.deployment_target == 'test_open_login_page_from_about_page'"
        run: pytest test_about_page.py::test_open_about_page_from_login_page


