name: Automated tests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        options:
          - Run smoke tests
          - Run all tests
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'Run smoke tests'"
        run: pytest -m smoke
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'Run all tests'"
        run: pytest


