name: Automated tests
on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        type: choice
        options:
          - Run smoke tests
          - Run regress tests
          - Run all tests

permissions:
  id-token: write
  pages: write

jobs:
  download-history:
    runs-on: ubuntu-latest
    name: Download history
    steps:
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Assign allure-results artifact for variable
        run: >
          ARTIFACT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          "https://api.github.com/repos/zor1497/saucedemo_testing/actions/artifacts?name=allure-results"
          | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/zor1497/saucedemo_testing/actions/artifacts/$ARTIFACT_ID/zip -o artifacts.zip
          &&
          REPORT_ID=$(curl -L 
          -H "Accept: application/vnd.github+json"
          -H "X-GitHub-Api-Version: 2022-11-28"
          "https://api.github.com/repos/zor1497/saucedemo_testing/actions/artifacts?name=github-pages"
          | python3 -c "import sys, json; print(json.load(sys.stdin)['artifacts'][0]['id']);")
          &&
          curl -L 
          -H "Accept: application/vnd.github+json" 
          -H "Authorization: Bearer ${{ secrets.TOKEN }}" 
          -H "X-GitHub-Api-Version: 2022-11-28" 
          https://api.github.com/repos/zor1497/saucedemo_testing/actions/artifacts/$REPORT_ID/zip -o page_s.zip
      - name: Unzip allure results
        run: mkdir allure-results && unzip artifacts.zip -d allure-results
      - name: Unzip old pages
        run: mkdir old-pages pages-history && unzip page_s.zip -d old-pages && tar -xvf old-pages/artifact.tar -C pages-history
      - name: Copy pages-history into allure-results
        run: cp pages-history/history/* allure-results && cp -r pages-history/history allure-results
      - name: Store allure history
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  run-tests:
    runs-on: ubuntu-latest
    name: Run tests
    needs: download-history
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Run smoke tests
        if: "github.event.inputs.deployment_target == 'Run smoke tests'"
        run: pytest -m smoke --alluredir=allure-results
      - name: Run all tests
        if: "github.event.inputs.deployment_target == 'Run all tests'"
        run: pytest --alluredir=allure-results
      - name: Run regress tests
        if: "github.event.inputs.deployment_target == 'Run regress tests'"
        run: pytest -m regress --alluredir=allure-results
      - name: Store allure results
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results

  generate-report:
    runs-on: ubuntu-latest
    needs: run-tests
    name: Generate report
    steps:
      - name: Install java
        uses: actions/setup-java@v4
        with:
          distribution: 'microsoft'
          java-version: '21'
      - name: Install allure
        run: sudo wget https://github.com/allure-framework/allure2/releases/download/2.29.0/allure-2.29.0.tgz && tar -xvzf allure-2.29.0.tgz -C /opt/ && sudo ln -s /opt/allure-2.29.0/bin/allure /usr/bin/allure
      - name: Download artifacts
        uses: actions/download-artifact@v4
      - name: Generate report
        run: allure generate -c allure-results -o _site
      - name: Store generated report
        uses: actions/upload-artifact@v4
        with:
          name: _site
          path: _site

  publish-report:
    runs-on: ubuntu-latest
    needs: generate-report
    name: Publish report
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
      - name: Deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v4



